# Generated by Django 4.2 on 2023-04-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=25)),
                ('event_dis', models.TextField()),
                ('event_prize', models.IntegerField(default=0)),
                ('event_pic', models.ImageField(upload_to='eventpics')),
                ('event_redirect_link', models.URLField()),
            ],
        ),
    ]
