# Generated by Django 4.2 on 2023-05-04 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_event_mode_event_is_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_closing_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 14, 49, 1, 298161)),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_open_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 14, 49, 1, 298161)),
        ),
    ]
