# Generated by Django 4.2 on 2023-05-15 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_stripe_prize_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=10)),
                ('speaker_pic', models.ImageField(upload_to='speakerpics')),
                ('speaker_details', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_closing_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 21, 42, 6, 384726)),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_open_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 21, 42, 6, 384726)),
        ),
    ]
