# Generated by Django 4.2 on 2023-05-15 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_speaker_event_speaker_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speaker_pic',
            field=models.ImageField(default='defaultpic.jpg', upload_to='speakerpics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_closing_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 21, 51, 9, 537504)),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_open_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 21, 51, 9, 537504)),
        ),
    ]
