# Generated by Django 4.2 on 2023-05-15 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_registration_closing_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='stripe_prize_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_closing_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 21, 55, 28, 508146)),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_open_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 21, 55, 28, 508146)),
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker_pic',
            field=models.ImageField(default='/defaultpic.jpg', upload_to='speakerpics'),
        ),
    ]
